application: loltools
version: 1
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static
- url: /
  script: _go_app
- url: /admin/.*
  script: _go_app
  login: admin
- url: /api/admin/.*
  script: _go_app
  login: admin
- url: /.*
  script: _go_app
  login: required
